# Generated by Django 4.2.4 on 2023-09-14 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('n_child', models.CharField(max_length=100, null=True)),
                ('n_adult', models.CharField(max_length=100, null=True)),
                ('checkIn', models.CharField(max_length=100, null=True)),
                ('checkOut', models.CharField(max_length=100, null=True)),
                ('rooms', models.CharField(max_length=100, null=True)),
                ('message', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('subject', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SiteName', models.CharField(max_length=100)),
                ('SiteContact', models.CharField(max_length=100)),
                ('SiteEmail', models.EmailField(max_length=254)),
                ('SiteAddress', models.CharField(max_length=500)),
                ('Sitedescription', models.CharField(max_length=500, null=True)),
                ('Sitefacebooklink', models.CharField(max_length=300)),
                ('Sitelinkdinlink', models.CharField(max_length=300)),
                ('Siteinstagramlink', models.CharField(max_length=300, null=True)),
                ('logo', models.ImageField(default=None, max_length=200, null=True, upload_to='logo/')),
                ('back_image', models.ImageField(null=True, upload_to='background/')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='rooms/')),
                ('description', models.TextField(null=True)),
                ('n_bed', models.IntegerField()),
                ('n_bath', models.IntegerField()),
                ('wifi', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rooms_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(null=True, upload_to='rooms/')),
                ('description', models.TextField(null=True)),
                ('n_bed', models.IntegerField(null=True)),
                ('n_bath', models.IntegerField(null=True)),
                ('wifi', models.IntegerField(null=True)),
                ('price', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('caption', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Publish', 'Publish'), ('Draft', 'Draft')], max_length=50)),
                ('position', models.IntegerField()),
                ('page_type', models.CharField(blank=True, choices=[('Home', 'Home'), ('Normal', 'Normal'), ('Group', 'Group'), ('Home/Slider', 'Home/Slider'), ('About', 'About'), ('Service', 'Service'), ('Testimonial', 'Testimonial'), ('Our Team', 'Our Team'), ('Service', 'Service'), ('Contact', 'Contact'), ('Booking', 'Booking')], max_length=50, null=True)),
                ('title', models.CharField(max_length=200)),
                ('short_desc', models.TextField(null=True)),
                ('desc', models.CharField(max_length=3000, null=True)),
                ('bannerimage', models.ImageField(null=True, upload_to='bannerimage/')),
                ('meta_title', models.CharField(max_length=100, null=True)),
                ('meta_keyword', models.CharField(max_length=100, null=True)),
                ('icon_image', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='image/')),
                ('slider_image', models.ImageField(null=True, upload_to='sliderimage/')),
                ('brochure', models.FileField(null=True, upload_to='brochure/')),
                ('Parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='adminpanel.navigation')),
            ],
        ),
    ]
