# Generated by Django 4.2.4 on 2023-09-14 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_booking_n_rooms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms_detail',
            old_name='name',
            new_name='f_name',
        ),
    ]
