# Generated by Django 4.2.4 on 2023-09-18 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_rename_name_rooms_detail_f_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms_detail',
            old_name='f_name',
            new_name='name',
        ),
    ]
