# Generated by Django 4.2.4 on 2023-09-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_rename_f_name_rooms_detail_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms_detail',
            name='n_bath',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rooms_detail',
            name='n_bed',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rooms_detail',
            name='price',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rooms_detail',
            name='wifi',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
